pipeline {
    agent any

    stages {
        stage('Build') {
            dir('Source/client') {
                steps {
                    sh '''
                        pwd
                        npm install
                        npm build
                    '''
                }
            }
        }
        // stage('Test') {
        //     steps {
        //         sh 'npm test'
        //     }
        // }
        // stage('Deploy') {
        //     steps {
        //         sh 'npm run deploy'
        //     }
        // }
    }
}
