pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                dir('Source/server') {
                    sh 'pwd'
                    sh 'npm install'
                    sh 'npm run format'
                }
            }
        }
        // stage('Test') {
        //     steps {
        //         sh 'npm test'
        //     }
        // }
        // stage('Deploy') {
        //     steps {
        //         sh 'npm run deploy'
        //     }
        // }
    }
}
